#%RAML 1.0 NamedExample
value:
    totalResults: 1
    responseSize: 1
    offset: 0
    limit: 25
    resultList:
    - id: 1
      userId: 1
      type: "Mobile"
      value: "+0901910191"
      preferred: true


    